# Generated by Django 6.0.4 on 2026-04-29 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member_name', models.CharField(max_length=100)),
                ('membership_id', models.CharField(max_length=40)),
                ('visit_date', models.DateField()),
                ('overall_experience', models.CharField(choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('unsatisfied', 'Unsatisfied'), ('very_unsatisfied', 'Very Unsatisfied')], max_length=20)),
                ('visit_reasons', models.JSONField(blank=True, default=list)),
                ('staff_service', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('facility_cleanliness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('amenities', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('dining_experience', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True)),
                ('activity_comfort', models.CharField(blank=True, choices=[('too_light', 'Too light'), ('too_strong', 'Too strong'), ('perfect', 'Just right')], max_length=20, null=True)),
                ('concerns_addressed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('recommend_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('follow_up', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Club feedback',
                'verbose_name_plural': 'Club feedback',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('front_desk', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('housekeeping', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('restaurant', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('cleanliness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('amenities', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('pool_fitness', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hotel feedback',
                'verbose_name_plural': 'Hotel feedback',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visit_date', models.DateField()),
                ('resident_name', models.CharField(blank=True, max_length=100)),
                ('outlet_visited', models.CharField(choices=[('deli_cafe', 'Deli Café'), ('aqua', 'Aqua'), ('on_nine', 'On Nine'), ('whisky_mist', 'Whisky Mist')], max_length=20)),
                ('food_quality', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('food_presentation', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_quality', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('staff_courtesy', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ambience', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('decor', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('music', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_satisfaction', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Restaurant feedback',
                'verbose_name_plural': 'Restaurant feedback',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('service_date', models.DateField()),
                ('overall_spa_experience', models.CharField(choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('unsatisfied', 'Unsatisfied'), ('very_unsatisfied', 'Very Unsatisfied')], max_length=20)),
                ('therapy_reasons', models.JSONField(blank=True, default=list)),
                ('massage_pressure', models.CharField(choices=[('too_light', 'Too light'), ('too_hard', 'Too hard'), ('perfect', 'Perfect')], max_length=20)),
                ('concerns_addressed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('therapist_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('follow_up', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
            options={
                'verbose_name': 'Spa feedback',
                'verbose_name_plural': 'Spa feedback',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
    ]
