# Generated by Django 6.0.4 on 2026-04-30 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_usermaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubfeedback',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='clubfeedback',
            name='membership_id',
        ),
        migrations.RemoveField(
            model_name='hotelfeedback',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='restaurantfeedback',
            name='resident_name',
        ),
        migrations.RemoveField(
            model_name='spafeedback',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='spafeedback',
            name='last_name',
        ),
        migrations.AddField(
            model_name='clubfeedback',
            name='flat_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clubfeedback',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clubfeedback',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, +, -, spaces, parentheses).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AddField(
            model_name='hotelfeedback',
            name='flat_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelfeedback',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hotelfeedback',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, +, -, spaces, parentheses).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AddField(
            model_name='restaurantfeedback',
            name='flat_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantfeedback',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurantfeedback',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, +, -, spaces, parentheses).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AddField(
            model_name='spafeedback',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='spafeedback',
            name='flat_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='spafeedback',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='spafeedback',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, +, -, spaces, parentheses).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='clubfeedback',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hotelfeedback',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hotelfeedback',
            name='room_number',
            field=models.CharField(choices=[('902', '902'), ('903', '903'), ('904', '904'), ('905', '905'), ('906', '906'), ('907', '907'), ('908', '908'), ('909', '909')], max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurantfeedback',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
